apiVersion: apps/v1
kind: Deployment 
metadata:
  name: wooless
  labels:
    app: wooless
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wooless
  template:
    metadata: 
      labels:
        app: wooless
    spec:
      containers:
        - name: wooless
          image: romiafrizal/wooless-web:latest
          resources:
            requests:
              cpu: "100m"
              memory: "100M"
            limits:
              cpu: 1024m
              memory: 2048M
  
